main: me.RICHicken.ManhuntWithMobs.Main
name: ManhuntWithMobs
version: 1.0
author: RICHicken
depend: [LibsDisguises]
commands:
  harassplayer:
   description: Starts the MobsvsSpeedrunner Gamemode.
   aliases: [harass]
  gettags:
   description: (Used for debugging) Tells user a Player's tags.
  stopharass:
   description: Stops the MobsvsSpeedrunner Gamemode.
  disguisecheck:
   description: Checks if player is diguised. (Used for debugging).
   togglecrawlmode:
     description: Toggle "Crawl Mode". When the speedrunner dies, the hunter who killed the speedrunner will become the speedrunner.